### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by geoffharcourt**
- bring back gem-installed executables as a temporary measure
- fixes for breaking Heroku CLI changes

### CODE REVIEW

**Comment by geoffharcourt** [comment]
This is not working in local testing against a real app, but I'm unsure if this is a temporary Heroku outage or not.

**Comment by eebs** [comment]
Thanks for the quick work to fix the Heroku CLI issues. I checked out this branch, built and packaged, and was able to run both a `staging backup` and `development restore staging`:

```
$ /Users/eebs/code/thoughtbot/parity/parity-2.0.0-osx/lib/app/bin/staging backup
Starting backup of postgresql-adjacent-55724... done

Use Ctrl-C at any time to stop monitoring progress; the backup will continue running.
Use heroku pg:backups:info to check progress.
Stop a running backup with heroku pg:backups:cancel.

Backing up DATABASE to b007... done
$ /Users/eebs/code/thoughtbot/parity/parity-2.0.0-osx/lib/app/bin/development restore staging
# restored correctly.
```

Hope this helps!

**Comment by geoffharcourt** [comment]
@eebs thanks for the help! I will recheck when I have some time later today, and if things work as expected I'll cut a new version on Rubygems and update Homebrew.

**Comment by geoffharcourt** [comment]
I'm still getting 503 errors from Heroku on the backup operation for two apps for which I have access.

**Pull request merged**
