### PR TITLE
Return 0 or 1 exit status code

### PR DESCRIPTION
**Pull request by croaky**
Kernel#exit

http://ruby-doc.org/core-2.2.2/Kernel.html#method-i-exit

### CODE REVIEW

**Comment by croaky** [comment]
Tested before:

```
% production backup
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
% echo $?
0
```

After:

```
% production backup
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
% echo $?
1
```

**Comment by geoffharcourt** [comment]
Nice! Is this worth doing an integration test against? (This might be a lot of effort for only a little gain.)

**Comment by croaky** [comment]
If we had one for the `bin` files before, I would have updated it, but since we don't, it felt like it was okay to manually test. What do you think?

**Comment by geoffharcourt** [comment]
I think the criterion you're using here is fine. Given that this was easy to test manually, I don't see a big problem in going ahead as is.

**Pull request merged**
