### PR TITLE
Update to Ruby 2.2.3

### PR DESCRIPTION
**Pull request by geoffharcourt**

### CODE REVIEW

**Comment by geoffharcourt** [comment]
@joelQ, does updating the version of Ruby we do development against have an effect on the packaging for Homebrew/apt?

**Comment by JoelQ** [comment]
It shouldn't affect the distribution since we package traveling ruby directly with code. We don't include the `.ruby-version` in the packages (see https://github.com/thoughtbot/parity/blob/master/Rakefile#L58-L66) so it probably only affects development of Parity.

That being said, it's probably a good idea to update the Ruby version shipped with traveling ruby as well. That way we are developing and testing against the same version that will be used in "production".

The traveling ruby version used for the packages is set here: https://github.com/thoughtbot/parity/blob/master/Rakefile#L10

**Comment by geoffharcourt** [comment]
Travelling Ruby is at 2.2.2, I'm going to update to get them both in sync.

**Comment by JoelQ** [comment]
:+1:

**Pull request merged**
